/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/animated-robot.glb --types --shadows=false -o src/world/RobotModel.tsx

Source: "Animated Robot" by Quaternius — https://poly.pizza/m/QCm7qe9uNJ
License: CC0 1.0 (Public Domain) — verified on the model page.
Processed: gltf-transform optimize --compress meshopt (401 KB → 168 KB).
Notes:
  - Animation clips are NOT played (the scene's procedural motion system is
    the driver), so `useAnimations` is intentionally omitted.
  - The head meshes are wrapped in a named `Head` group so Robot.tsx can scan
    the head procedurally (this model's skeleton only drives the hands).
  - The GLB URL is basePath-aware: the static export serves the site from
    /aquaguardian (see next.config.ts), while `next dev` serves from /.
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, ThreeElements } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const MODEL_URL =
  typeof window !== 'undefined' && window.location.pathname.startsWith('/aquaguardian')
    ? '/aquaguardian/models/animated-robot.glb'
    : '/models/animated-robot.glb'

/** Neck pivot of the model's Head group (model units). */
const HEAD_PIVOT_Y = 2.9

type GLTFResult = {
  nodes: {
    FootL_1: THREE.Mesh
    LowerLegL_1: THREE.Mesh
    LegL: THREE.Mesh
    LowerLegR_1: THREE.Mesh
    LegR: THREE.Mesh
    Head_2: THREE.Mesh
    Head_3: THREE.Mesh
    Head_4: THREE.Mesh
    ArmL: THREE.Mesh
    ShoulderL_1: THREE.Mesh
    ArmR: THREE.Mesh
    ShoulderR_1: THREE.Mesh
    Torso_2: THREE.Mesh
    Torso_3: THREE.Mesh
    FootR_1: THREE.Mesh
    HandR_1: THREE.SkinnedMesh
    HandR_2: THREE.SkinnedMesh
    HandL_1: THREE.SkinnedMesh
    HandL_2: THREE.SkinnedMesh
    Bone: THREE.Bone
  }
  materials: {
    Grey: THREE.MeshStandardMaterial
    Main: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function RobotModel({
  headRef,
  children,
  ...props
}: ThreeElements['group'] & {
  /** Ref to the model's Head group (neck pivot) so Robot.tsx can scan it. */
  headRef?: React.Ref<THREE.Group>
  children?: React.ReactNode
}) {
  const group = React.useRef<THREE.Group>(null)
  const { scene } = useGLTF(MODEL_URL)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Bone} />
        <group name="HandR" position={[-0.003, 2.37, -0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="HandR_1" geometry={nodes.HandR_1.geometry} material={materials.Main} skeleton={nodes.HandR_1.skeleton} />
          <skinnedMesh name="HandR_2" geometry={nodes.HandR_2.geometry} material={materials.Grey} skeleton={nodes.HandR_2.skeleton} />
        </group>
        <group name="HandL" position={[-0.003, 2.37, -0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="HandL_1" geometry={nodes.HandL_1.geometry} material={materials.Main} skeleton={nodes.HandL_1.skeleton} />
          <skinnedMesh name="HandL_2" geometry={nodes.HandL_2.geometry} material={materials.Grey} skeleton={nodes.HandL_2.skeleton} />
        </group>
        {/* Named group so Robot.tsx can scan the head procedurally (neck pivot). */}
        <group ref={headRef} name="Head" position={[0, HEAD_PIVOT_Y, 0]}>
          <mesh name="Head_2" geometry={nodes.Head_2.geometry} material={materials.Grey} />
          <mesh name="Head_3" geometry={nodes.Head_3.geometry} material={materials.Main} />
          <mesh name="Head_4" geometry={nodes.Head_4.geometry} material={materials.Black} />
          {children}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_URL)
