#!/usr/bin/env python3
"""
AquaGuardian asset integrity gate (Python 3).

Every path the project claims to ship — README screenshots, favicon set, OG
image, web manifest icons, sitemap targets, robots, and the generated data
artifacts — must actually exist on disk. Screenshots silently rot, icons get
renamed, and pages 404; this script is the tripwire. Exits non-zero when any
*required* asset is missing.

The reference list is data-driven (REFERENCE_ASSETS below) and mirrors what
the README, src/app/layout.tsx metadata, public/site.webmanifest, and
public/sitemap.xml point at, so a change in one place is caught here.

Usage:
    python scripts/validate_assets.py                 # full check
    python scripts/validate_assets.py --quiet         # only problems
    python scripts/validate_assets.py --json          # machine-readable report
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
PUBLIC_DIR = ROOT_DIR / "public"
SCREENSHOT_DIR = ROOT_DIR / "assets" / "screenshots"

# (path relative to repo root, required?) — update when the app's references change.
REFERENCE_ASSETS: list[tuple[str, bool]] = [
    # README screenshot gallery
    ("assets/screenshots/hero.png", True),
    ("assets/screenshots/dashboard.png", True),
    ("assets/screenshots/missions.png", True),
    ("assets/screenshots/learn.png", True),
    # layout.tsx metadata icons + OG
    ("public/favicon.ico", True),
    ("public/favicon-16x16.png", True),
    ("public/favicon-32x32.png", True),
    ("public/favicon-48x48.png", True),
    ("public/favicon.svg", True),
    ("public/apple-touch-icon.png", True),
    ("public/og-image.png", True),
    ("public/og-image.svg", True),
    # PWA manifest + robots + sitemap (referenced by layout.tsx / Next metadata)
    ("public/site.webmanifest", True),
    ("public/robots.txt", True),
    ("public/sitemap.xml", True),
    ("public/social-banner.svg", True),
    # generated data pipeline output (consumed by the dashboard)
    ("src/data/ocean_analysis.json", True),
    # native pipeline input — generated by scripts/native/ocean_metrics.c;
    # optional until the C toolchain has been run on this machine.
    ("database.json", False),
]


def manifest_icon_refs() -> list[str]:
    """Resolve icon srcs from site.webmanifest into repo-relative paths."""
    manifest_path = PUBLIC_DIR / "site.webmanifest"
    if not manifest_path.is_file():
        return []
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    refs = []
    for icon in manifest.get("icons", []):
        src = str(icon.get("src", ""))
        # Icon srcs are basePath-qualified (/aquaguardian/...) — strip the prefix.
        stripped = src.lstrip("/").split("/", 1)[-1] if "/" in src.lstrip("/") else src
        refs.append(f"public/{stripped}")
    return refs


BASE_PATH = "aquaguardian"  # must match the basePath in next.config.ts


def sitemap_routes() -> list[str]:
    """Extract app routes from sitemap.xml URLs, e.g. ['', 'privacy']."""
    sitemap_path = PUBLIC_DIR / "sitemap.xml"
    if not sitemap_path.is_file():
        return []
    text = sitemap_path.read_text(encoding="utf-8")
    routes: list[str] = []
    for line in text.splitlines():
        if "<loc>" not in line:
            continue
        url = line.replace("<loc>", "").replace("</loc>", "").strip()
        path_part = url.split("//", 1)[-1].split("/", 1)[-1].strip("/")
        # Strip the GitHub Pages basePath (sitemap URLs are basePath-qualified).
        if path_part == BASE_PATH:
            path_part = ""
        elif path_part.startswith(BASE_PATH + "/"):
            path_part = path_part[len(BASE_PATH) + 1 :]
        if path_part and path_part.startswith(("http", "www")):
            continue  # external URL: nothing to check on disk
        routes.append(path_part)
    return routes


def route_candidates(route: str) -> list[str]:
    """Where a sitemap route may live on disk, in preference order."""
    if route in ("", "/", "index"):
        return ["src/app/page.tsx", "out/index.html"]
    return [
        f"src/app/{route}/page.tsx",
        f"src/app/{route}.tsx",
        f"out/{route}/index.html",
        f"public/{route}/index.html",
    ]


def collect_references() -> list[tuple[str, bool]]:
    refs = list(REFERENCE_ASSETS)
    for icon_path in manifest_icon_refs():
        refs.append((icon_path, True))
    for route in sitemap_routes():
        candidates = route_candidates(route)
        hit = next((c for c in candidates if (ROOT_DIR / c).is_file()), None)
        if hit is None:
            hit = candidates[0]  # report the canonical source path as missing
        refs.append((hit, True))
    # De-duplicate while preserving order.
    seen: set[str] = set()
    unique: list[tuple[str, bool]] = []
    for path, required in refs:
        if path not in seen:
            seen.add(path)
            unique.append((path, required))
    return unique


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quiet", action="store_true", help="only print problems")
    parser.add_argument("--json", action="store_true", help="emit JSON report")
    args = parser.parse_args()

    references = collect_references()
    results = []
    for rel_path, required in references:
        exists = (ROOT_DIR / rel_path).is_file()
        results.append(
            {
                "path": rel_path,
                "required": required,
                "exists": exists,
            }
        )

    if args.json:
        print(json.dumps({"results": results}, indent=2))
        return 0 if all(r["exists"] or not r["required"] for r in results) else 1

    missing_required = [r for r in results if not r["exists"] and r["required"]]
    missing_optional = [r for r in results if not r["exists"] and not r["required"]]

    if not args.quiet:
        checked = len(results)
        present = sum(1 for r in results if r["exists"])
        print(f"[INFO] AquaGuardian asset gate: {present}/{checked} assets present")
        print(f"[INFO] ({len(missing_optional)} optional, {len(missing_required)} required missing)")
        for r in results:
            if r["exists"]:
                print(f"  [OK]   {r['path']}")
            else:
                kind = "OPTIONAL" if not r["required"] else "REQUIRED"
                print(f"  [{'MISS' if r['required'] else 'SKIP'}] {kind:8s} {r['path']}")

    if missing_optional:
        for r in missing_optional:
            print(f"[WARN] optional asset missing: {r['path']} (generate via the C tool)")

    if missing_required:
        for r in missing_required:
            print(f"[FAIL] required asset missing: {r['path']}")
        print(f"[FAIL] {len(missing_required)} required asset(s) missing")
        return 1

    print("[SUCCESS] all required assets are present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
