'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { impactFacts, missionBlueprints } from '@/data/impactData'
import oceanAnalysis from '@/data/ocean_analysis.json'

interface PipelineMetrics {
  totalItemsCollected: number
  totalWeightKg: number
  estimatedCo2SavedKg: number
  totalCollectionEvents: number
  topCollectionZone: string
  generatedAt: string
}

interface StatsResponse {
  collections?: Array<{ amount: number; location: string; timestamp: string }>
  totalPlastic?: number
  pipeline?: PipelineMetrics
}

export default function DashboardPage() {
  const [stats, setStats] = useState<StatsResponse>({})
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    let active = true

    fetch('/api/stats')
      .then((res) =>
        res.ok ? res.json() : Promise.reject(new Error('stats unavailable'))
      )
      .then((data) => {
        if (active) {
          setStats(data)
          setLoading(false)
        }
      })
      .catch(() => {
        if (active) {
          // Static export has no API routes (CI removes src/app/api), so fall
          // back to the build-time dataset generated by the native pipeline:
          // ocean_metrics.c -> database.json -> analyze_ocean_data.py ->
          // src/data/ocean_analysis.json.
          setStats({
            collections: [],
            totalPlastic: oceanAnalysis.metrics.totalItemsCollected,
            pipeline: {
              ...oceanAnalysis.metrics,
              generatedAt: oceanAnalysis.generatedAt,
            },
          })
          setLoading(false)
        }
      })

    return () => {
      active = false
    }
  }, [])

  const totalCollected = useMemo(() => {
    if (stats.pipeline) return stats.pipeline.totalItemsCollected
    const entries = stats.collections ?? []
    return entries.reduce((sum, entry) => sum + (entry.amount ?? 0), 0)
  }, [stats])

  const trackedEntries = useMemo(() => {
    if (stats.pipeline) return stats.pipeline.totalCollectionEvents
    return stats.collections?.length ?? 0
  }, [stats])

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(0,229,255,0.14),_transparent_35%),_#010B13] px-6 py-16 text-white">
      <div className="mx-auto flex max-w-7xl flex-col gap-10">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-sm uppercase tracking-[0.3em] text-gold-400/80">Ocean Impact Dashboard</p>
            <h1 className="mt-2 text-4xl font-semibold tracking-[0.08em] text-white sm:text-5xl">
              Live conservation context, grounded in real-world evidence.
            </h1>
          </div>
          <Link href="/" className="rounded-full border border-gold-400/30 px-4 py-2 text-sm text-gold-400 transition hover:border-gold-400/60 hover:bg-gold-400/10">
            Back to story
          </Link>
        </div>

        <section className="grid gap-4 md:grid-cols-3">
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl">
            <p className="text-sm uppercase tracking-[0.3em] text-cyan-400/80">Tracked entries</p>
            <p className="mt-3 text-3xl font-semibold">{loading ? '…' : trackedEntries}</p>
            <p className="mt-2 text-sm text-text-muted">Submitted through the app’s collection API.</p>
          </div>
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl">
            <p className="text-sm uppercase tracking-[0.3em] text-cyan-400/80">Estimated impact</p>
            <p className="mt-3 text-3xl font-semibold">{loading ? '…' : `${totalCollected} pieces`}</p>
            <p className="mt-2 text-sm text-text-muted">A practical local tally from the app’s data feed.</p>
          </div>
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl">
            <p className="text-sm uppercase tracking-[0.3em] text-cyan-400/80">Reference basis</p>
            <p className="mt-3 text-3xl font-semibold">Real data</p>
            <p className="mt-2 text-sm text-text-muted">Metrics are anchored to published conservation and ocean assessments.</p>
          </div>
        </section>

        {stats.pipeline && (
          <p className="text-xs uppercase tracking-[0.25em] text-cyan-400/60">
            Offline telemetry: native C → Python pipeline · generated {stats.pipeline.generatedAt} · top zone{' '}
            {stats.pipeline.topCollectionZone} · est. {stats.pipeline.totalWeightKg} kg ·{' '}
            {stats.pipeline.estimatedCo2SavedKg} kg CO₂ offset
          </p>
        )}

        <section className="grid gap-6 lg:grid-cols-[1.3fr_0.9fr]">
          <div className="rounded-3xl border border-white/10 bg-[#041525]/80 p-8 shadow-[0_20px_80px_rgba(0,0,0,0.3)]">
            <h2 className="text-2xl font-semibold text-white">Evidence-backed ocean context</h2>
            <div className="mt-6 space-y-4">
              {impactFacts.map((fact) => (
                <motion.div
                  key={fact.title}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="rounded-2xl border border-white/10 bg-white/5 p-4"
                >
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-lg font-medium text-white">{fact.title}</p>
                    <span className="rounded-full bg-gold-400/10 px-3 py-1 text-sm text-gold-400">{fact.value}</span>
                  </div>
                  <p className="mt-2 text-sm leading-6 text-text-muted">{fact.detail}</p>
                  <p className="mt-2 text-xs uppercase tracking-[0.25em] text-cyan-400/70">Source: {fact.source}</p>
                </motion.div>
              ))}
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/5 p-8 backdrop-blur-xl">
            <h2 className="text-2xl font-semibold text-white">Mission blueprints</h2>
            <div className="mt-6 space-y-4">
              {missionBlueprints.map((item) => (
                <div key={item.name} className="rounded-2xl border border-white/10 bg-[#010B13]/70 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-lg font-medium text-white">{item.name}</p>
                    <span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs uppercase tracking-[0.25em] text-cyan-400">{item.status}</span>
                  </div>
                  <p className="mt-2 text-sm text-text-muted">{item.focus}</p>
                  <p className="mt-2 text-xs uppercase tracking-[0.25em] text-gold-400/70">{item.evidence}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>
    </main>
  )
}
